[package]
name = "huffzip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
counter = "0.7.0"
num-traits = "0.2.19"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = "1.0.228"
sha256 = "1.6.0"
